services:
  - type: web
    name: signlang-ai
    runtime: python
    region: oregon
    plan: free
    rootDir: jars_project_onnx
    buildCommand: pip install --upgrade pip && pip install -r requirements-render.txt
    startCommand: gunicorn -c gunicorn_conf.py server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: CORS_ORIGINS
        sync: false
